name: Main
on:
  push:
    branches:
      - main

jobs:
  install:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Install
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: npm run test

  semantic-version:
    name: Semantic Release
    needs: install
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx -p pinst -p semantic-release -p @semantic-release/git -p @semantic-release/changelog -p @semantic-release/exec -p semantic-release-github semantic-release --provider=github --debug=true

  build:
    name: Build
    needs: semantic-version
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Build
        run: |
          npm run generate
          touch packages/sample/dist/.nojekyll
        env:
          WEBSITE_HOST: https://grabarzundpartner.github.io
          BASE_PATH: /foundation/
          DIST_PATH: dist
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: artifact
          path: packages/sample/dist

  deploy-ghpages:
    name: Deploy (GH-Pages)
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: artifact
          path: public
      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
